// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About/index.vue')['default']
    AboutOption: typeof import('./components/AboutOption/index.vue')['default']
    Basic: typeof import('./components/Basic/index.vue')['default']
    Button: typeof import('./components/Button/index.vue')['default']
    Check: typeof import('./components/Check/index.vue')['default']
    File: typeof import('./components/File/index.vue')['default']
    GenshinImpact: typeof import('./components/Options/GenshinImpact/index.vue')['default']
    GloryOfTheKing: typeof import('./components/Options/GloryOfTheKing/index.vue')['default']
    HelpCentre: typeof import('./components/HelpCentre/index.vue')['default']
    InputBox: typeof import('./components/InputBox/index.vue')['default']
    Item: typeof import('./components/Item/index.vue')['default']
    LeagueofLegend: typeof import('./components/Options/LeagueofLegend/index.vue')['default']
    List: typeof import('./components/List/index.vue')['default']
    Options: typeof import('./components/Options/index.vue')['default']
    Order: typeof import('./components/Order/index.vue')['default']
    Price: typeof import('./components/Price/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
